commands:
    build:
      description: Build
      steps:
      - run:
          command: |
            echo 'build'
          name: Build
    calculate_test_result:
      description: Show persentage of failed specs
      steps:
      - run:
          command: |
            echo 'show result'
          when: always
    install:
      description: Install Dependencies
      steps:
      - run:
          command: |
            echo 'install deps'
          name: Install packages
    test-api:
      description: Test API
      steps:
        - run:
            command: |
              echo 'test api'
    test-local:
      description: Test checkout
      steps:
        - run:
            command: |
              echo 'test local'
    test-suite-local:
      description: Run test suite locally
      steps:
        - run:
            command: |
              echo 'test local'
    test-suite-b:
      description: Run tests on browserstack
      steps:
        - run:
            command: |
              echo 'test local'
  jobs:
    bs-base:
      docker:
      - image: circleci/openjdk:latest-node
      parameters:
        env:
          type: env_var_name
      steps:
      - test-suite-b:
          env: << parameters.env >>
          max_sessions: 7
          suite: checkout_base
      working_directory: /home/circleci/project
    test-job-1:
      docker:
      - image: circleci/openjdk:latest-node
      parameters:
        env:
          type: env_var_name
      steps:
        - run:
            command: |
              echo 'test job 1'
      working_directory: /home/circleci/project
    test-job-2:
      docker:
      - image: circleci/openjdk:latest-node
      parameters:
        env:
          type: env_var_name
      steps:
        - run:
            command: |
              echo 'test job 2'
      working_directory: /home/circleci/project
    test-job-3:
      docker:
      - image: circleci/openjdk:latest-node
      parameters:
        env:
          type: env_var_name
      steps:
        - run:
            command: |
              echo 'test job 3'
      working_directory: /home/circleci/project
    bs-miva:
      docker:
      - image: circleci/openjdk:latest-node
      parameters:
        env:
          type: env_var_name
      steps:
      - test-suite-b:
          env: << parameters.env >>
          max_sessions: 2
          suite: checkout_miva
          testRail: true
          testRailSuite: 306
      working_directory: /home/circleci/project
    bs-shopify:
      docker:
      - image: circleci/openjdk:latest-node
      parameters:
        env:
          type: env_var_name
      steps:
      - test-suite-b:
          env: << parameters.env >>
          max_sessions: 4
          suite: checkout_shopify
          testRail: true
          testRailSuite: 307
      working_directory: /home/circleci/project
    bs-smoke:
      docker:
      - image: circleci/openjdk:latest-node
      parameters:
        env:
          type: env_var_name
        sessions:
          type: integer
        suite:
          type: string
      steps:
      - test-suite-b:
          env: << parameters.env >>
          max_sessions: << parameters.sessions >>
          suite: << parameters.suite >>
      working_directory: /home/circleci/project
    bs-woocommerce-backend:
      docker:
      - image: circleci/openjdk:latest-node
      parameters:
        env:
          type: env_var_name
      steps:
      - test-suite-b:
          env: << parameters.env >>
          max_sessions: 2
          suite: checkout_woocommerce_back
          testRail: true
          testRailSuite: 229
      working_directory: /home/circleci/project
    bs-woocommerce-frontend:
      docker:
      - image: circleci/openjdk:latest-node
      parameters:
        env:
          type: env_var_name
      steps:
      - swissknife/wait_for_job:
          job-name: Sandbox BS woocommerce 1 tests
      - test-suite-b:
          env: << parameters.env >>
          max_sessions: 4
          suite: checkout_woocommerce_front
          testRail: true
          testRailSuite: 229
      working_directory: /home/circleci/project
    lint:
      docker:
      - image: circleci/node:latest
      resource_class: small
      steps:
      - checkout
      - swissknife/fail_if_dirty:
          custom-error-message: Please run circle_pack.sh and push up
          invert-pattern: false
          pattern: .*circleci/config.yml
          print-modified-files: true
          steps-to-run:
          - run:
              command: |
                curl -fLSs https://circle.ci/cli | sudo bash
                ./circle_pack.sh
              name: Generate Circle CI Config
              shell: /bin/bash
      working_directory: /home/circleci/project
    test-api:
      docker:
      - image: circleci/openjdk:latest-node
      steps:
      - test-api
      working_directory: /home/circleci/project
    test-local-chrome:
      docker:
      - image: circleci/openjdk:latest-node
      - image: selenium/standalone-chrome
      parallelism: 5
      parameters:
        env:
          type: env_var_name
        run_test_merchant:
          default: false
          type: boolean
      steps:
      - when:
          condition: always
          steps:
          - test-local:
              env: << parameters.env >>
              test: test-checkout
      - when:
          condition: always
          steps:
          - test-local:
              env: << parameters.env >>
              test: test-consumer
      - when:
          condition: << parameters.run_test_merchant >>
          steps:
          - test-local:
              env: << parameters.env >>
              test: test-merchant
      working_directory: /home/circleci/project
  orbs:
    swissknife: roopakv/swissknife@0.12.0
  parameters:
    acceptance_config:
      default: '{}'
      type: string
    run_base_tests:
      default: true
      type: boolean
    run_cdstaging_integration_tests:
      default: false
      type: boolean
    run_m2_acceptance_tests:
      default: false
      type: boolean
    run_production_integration_tests:
      default: false
      type: boolean
    run_regression_sandbox:
      default: false
      type: boolean
    run_regression_staging:
      default: false
      type: boolean
    run_sandbox_integration_tests:
      default: false
      type: boolean
    run_smoke_sandbox:
      default: false
      type: boolean
    run_smoke_staging:
      default: false
      type: boolean
    run_staging_integration_tests:
      default: false
      type: boolean
  version: 2.1
  workflows:
    build:
      jobs:
      - test-local-chrome:
          context: integration-tests-secrets
          env: TEST_ENV_STAGING
          name: Staging on local chrome
          requires:
          - lint
          run_test_merchant: true
      - test-local-chrome:
          context: integration-tests-secrets
          env: TEST_ENV_SANDBOX
          name: Sandbox on local chrome
          requires:
          - lint
      - test-api:
          context: integration-tests-secrets
          name: Staging API
          requires:
          - lint
      - lint
      when: << pipeline.parameters.run_base_tests >>
    m2-acceptance:
      jobs:
      - acceptance:
          context: integration-tests-secrets
          suite_type: m2_acceptance
      when: << pipeline.parameters.run_m2_acceptance_tests >>
    production:
      jobs:
      - swissknife/queue_up_workflow:
          max-wait-time: "1800"
          workflow-name: ^(staging|production|sandbox)$
      - test-local-chrome:
          context: integration-tests-secrets
          env: TEST_ENV_PRODUCTION
          name: Prod on local chrome
      - bs-base:
          context: integration-tests-secrets
          env: TEST_ENV_PRODUCTION
          name: Prod BS Base tests
          requires:
          - swissknife/queue_up_workflow
      when: << pipeline.parameters.run_production_integration_tests >>
    regression-sandbox:
      jobs:
      - swissknife/queue_up_workflow:
          max-wait-time: "1800"
          workflow-name: ^(staging|production|sandbox)$
      - test-local-chrome:
          context: integration-tests-secrets
          env: TEST_ENV_SANDBOX
          name: Local Chrome tests
      - bs-base:
          context: integration-tests-secrets
          env: TEST_ENV_SANDBOX
          name: BS TestBed tests
          requires:
          - swissknife/queue_up_workflow
      - bs-shopify:
          context: integration-tests-secrets
          env: TEST_ENV_SANDBOX
          name: BS Shopify tests
          requires:
          - swissknife/queue_up_workflow
      - test-job-1:
          context: integration-tests-secrets
          env: TEST_ENV_SANDBOX
          name: BS BigCommerce tests
          requires:
          - swissknife/queue_up_workflow
      - bs-woocommerce-backend:
          context: integration-tests-secrets
          env: TEST_ENV_SANDBOX
          name: BS WooCommerce BE tests
          requires:
          - swissknife/queue_up_workflow
      - bs-woocommerce-frontend:
          context: integration-tests-secrets
          env: TEST_ENV_SANDBOX
          name: BS WooCommerce FE tests
          requires:
          - swissknife/queue_up_workflow
      - bs-miva:
          context: integration-tests-secrets
          env: TEST_ENV_SANDBOX
          name: BS Miva tests
          requires:
          - swissknife/queue_up_workflow
      - test-job-2:
          context: integration-tests-secrets
          env: TEST_ENV_SANDBOX
          name: BS M1 tests
          requires:
          - swissknife/queue_up_workflow
      - test-job-3:
          context: integration-tests-secrets
          env: TEST_ENV_SANDBOX
          name: BS M2 tests
          requires:
          - swissknife/queue_up_workflow
      when: << pipeline.parameters.run_regression_sandbox >>
    regression-staging:
      jobs:
      - swissknife/queue_up_workflow:
          max-wait-time: "1800"
          workflow-name: ^(staging|production|sandbox)$
      - test-local-chrome:
          context: integration-tests-secrets
          env: TEST_ENV_STAGING
          name: Local Chrome tests
          run_test_merchant: true
      - bs-base:
          context: integration-tests-secrets
          env: TEST_ENV_STAGING
          name: BS TestBed tests
          requires:
          - swissknife/queue_up_workflow
      - bs-shopify:
          context: integration-tests-secrets
          env: TEST_ENV_STAGING
          name: BS Shopify tests
          requires:
          - swissknife/queue_up_workflow
      - test-job-1:
          context: integration-tests-secrets
          env: TEST_ENV_STAGING
          name: BS BigCommerce tests
          requires:
          - swissknife/queue_up_workflow
      - test-api:
          context: integration-tests-secrets
          name: API tests
      when: << pipeline.parameters.run_regression_staging >>
    sandbox:
      jobs:
      - swissknife/queue_up_workflow:
          max-wait-time: "1800"
          workflow-name: ^(staging|production|sandbox)$
      - test-local-chrome:
          context: integration-tests-secrets
          env: TEST_ENV_SANDBOX
          name: Sandbox on local chrome
      - bs-base:
          context: integration-tests-secrets
          env: TEST_ENV_SANDBOX
          name: Sandbox BS Base tests
          requires:
          - swissknife/queue_up_workflow
      - bs-shopify:
          context: integration-tests-secrets
          env: TEST_ENV_SANDBOX
          name: Sandbox BS Shopify tests
          requires:
          - swissknife/queue_up_workflow
      - test-job-1:
          context: integration-tests-secrets
          env: TEST_ENV_SANDBOX
          name: Sandbox BS bigcommerce tests
          requires:
          - swissknife/queue_up_workflow
      - bs-woocommerce-backend:
          context: integration-tests-secrets
          env: TEST_ENV_SANDBOX
          name: Sandbox BS woocommerce backend tests
          requires:
          - swissknife/queue_up_workflow
      - bs-woocommerce-frontend:
          context: integration-tests-secrets
          env: TEST_ENV_SANDBOX
          name: Sandbox BS woocommerce frontend tests
          requires:
          - swissknife/queue_up_workflow
      - bs-miva:
          context: integration-tests-secrets
          env: TEST_ENV_SANDBOX
          name: Sandbox BS miva tests
          requires:
          - swissknife/queue_up_workflow
      - test-job-2:
          context: integration-tests-secrets
          env: TEST_ENV_SANDBOX
          name: Sandbox BS magento1 tests
          requires:
          - swissknife/queue_up_workflow
      - test-job-3:
          context: integration-tests-secrets
          env: TEST_ENV_SANDBOX
          name: Sandbox BS magento2 tests
          requires:
          - swissknife/queue_up_workflow
      when: << pipeline.parameters.run_sandbox_integration_tests >>
    smoke-sandbox:
      jobs:
      - swissknife/queue_up_workflow:
          max-wait-time: "1800"
          workflow-name: ^(staging|production|sandbox)$
      - bs-smoke:
          context: integration-tests-secrets
          env: TEST_ENV_SANDBOX
          name: Smoke BS - Sandbox
          requires:
          - swissknife/queue_up_workflow
          sessions: 10
          suite: smoke_tests_sandbox
      - test-local-chrome:
          context: integration-tests-secrets
          env: TEST_ENV_SANDBOX
          name: Local Chrome - Sandbox
      when: << pipeline.parameters.run_smoke_sandbox >>
    smoke-staging:
      jobs:
      - test-api:
          context: integration-tests-secrets
          name: API - Staging
      - swissknife/queue_up_workflow:
          max-wait-time: "1800"
          workflow-name: ^(staging|production|sandbox)$
      - bs-smoke:
          context: integration-tests-secrets
          env: TEST_ENV_STAGING
          name: Smoke BS - Staging
          requires:
          - swissknife/queue_up_workflow
          sessions: 10
          suite: smoke_tests_staging
      - test-local-chrome:
          context: integration-tests-secrets
          env: TEST_ENV_STAGING
          name: Local Chrome - Staging
          run_test_merchant: true
      when: << pipeline.parameters.run_smoke_staging >>
    staging:
      jobs:
      - swissknife/queue_up_workflow:
          max-wait-time: "1800"
          workflow-name: ^(staging|production|sandbox)$
      - test-local-chrome:
          context: integration-tests-secrets
          env: TEST_ENV_STAGING
          name: Staging on local chrome
          run_test_merchant: true
      - bs-base:
          context: integration-tests-secrets
          env: TEST_ENV_STAGING
          name: Staging BS base tests
          requires:
          - swissknife/queue_up_workflow
      - bs-shopify:
          context: integration-tests-secrets
          env: TEST_ENV_STAGING
          name: Staging BS shopify tests
          requires:
          - swissknife/queue_up_workflow
      - test-job-1:
          context: integration-tests-secrets
          env: TEST_ENV_STAGING
          name: Staging BS bigcommerce tests
          requires:
          - swissknife/queue_up_workflow
      - test-api:
          context: integration-tests-secrets
          name: Staging API
      when: << pipeline.parameters.run_staging_integration_tests >>
    staging-local-chrome:
      jobs:
      - test-local-chrome:
          context: integration-tests-secrets
          env: TEST_ENV_STAGING
          name: Staging on local chrome
          run_test_merchant: true
      when: << pipeline.parameters.run_cdstaging_integration_tests >>
  
  