  jobs:
    bs-base:
      docker:
      - image: circleci/openjdk:latest-node
      parameters:
        env:
          type: env_var_name
      steps:
      - test-suite-b:
          env: << parameters.env >>
          max_sessions: 7
          suite: checkout_base
      working_directory: /home/circleci/project
    job-1:
      docker:
      - image: circleci/openjdk:latest-node
      parameters:
        env:
          type: env_var_name
      steps:
        - run:
            command: |
              sleep 10
              echo 'test job 1'
      working_directory: /home/circleci/project
    job-2:
      docker:
      - image: circleci/openjdk:latest-node
      parameters:
        env:
          type: env_var_name
      steps:
        - run:
            command: |
              echo 'test job 2'
      working_directory: /home/circleci/project
    job-3:
      docker:
      - image: circleci/openjdk:latest-node
      steps:
        - run:
            command: |
              echo 'test job 3'
      working_directory: /home/circleci/project
    lint:
      docker:
      - image: circleci/node:latest
      resource_class: small
      steps:
      - checkout
      - run:
          command: 'echo lint'
      working_directory: /home/circleci/project
    test-api:
      docker:
      - image: circleci/openjdk:latest-node
      steps:
      - test-api
      working_directory: /home/circleci/project
  orbs:
    swissknife: roopakv/swissknife@0.12.0
  parameters:
    run_base:
      default: true
      type: boolean
    run_sandbox_integration_tests:
      default: false
      type: boolean
  version: 2.1
  workflows:
    build:
      jobs:
      - job-1:
          env: TEST_ENV_STAGING
          name: Test job 1
          requires:
          - lint
      - job-2:
          env: TEST_ENV_SANDBOX
          name: Test job 2
          requires:
          - lint
      - job-3:
          name: Test job 3
          requires:
          - lint
      - lint
      when: << pipeline.parameters.run_base >>
    sandbox:
      jobs:
      - job-1:
          env: TEST_ENV_SANDBOX
          name: Test job 1
          requires:
          - lint
      - job-2:
          env: TEST_ENV_SANDBOX
          name: Test job 2
          requires:
          - lint
          - job-1
      - job-3:
          name: Test job 3
          requires:
          - lint
          - job-2
      - lint
      when: << pipeline.parameters.run_sandbox_integration_tests >>
